// Generated symbols file
//Re-regenerate from File > Packages > SymbolGeneratorPlugin
import Foundation
extension Symbol {
  public var num1: Symbol { append("1") }
  public var num27: Symbol { append("27") }
  public var num37: Symbol { append("37") }
  public var num29: Symbol { append("29") }
  public var num8: Symbol { append("8") }
  public var num00: Symbol { append("00") }
  public var num26: Symbol { append("26") }
  public var num39: Symbol { append("39") }
  public var num07: Symbol { append("07") }
  public var num24: Symbol { append("24") }
  public var num01: Symbol { append("01") }
  public var num3: Symbol { append("3") }
  public var num13: Symbol { append("13") }
  public var num42: Symbol { append("42") }
  public var num100percent: Symbol { append("100percent") }
  public var num5: Symbol { append("5") }
  public var num23: Symbol { append("23") }
  public var num0percent: Symbol { append("0percent") }
  public var num2d: Symbol { append("2d") }
  public var num28: Symbol { append("28") }
  public var num02: Symbol { append("02") }
  public var num75percent: Symbol { append("75percent") }
  public var num4h: Symbol { append("4h") }
  public var num3x1: Symbol { append("3x1") }
  public var num46: Symbol { append("46") }
  public var num17: Symbol { append("17") }
  public var num2x1: Symbol { append("2x1") }
  public var num33percent: Symbol { append("33percent") }
  public var num36: Symbol { append("36") }
  public var num9: Symbol { append("9") }
  public var num18: Symbol { append("18") }
  public var num1x2: Symbol { append("1x2") }
  public var num38: Symbol { append("38") }
  public var num34: Symbol { append("34") }
  public var num84percent: Symbol { append("84percent") }
  public var num4k: Symbol { append("4k") }
  public var num0: Symbol { append("0") }
  public var num4x3: Symbol { append("4x3") }
  public var num2: Symbol { append("2") }
  public var num67percent: Symbol { append("67percent") }
  public var num21: Symbol { append("21") }
  public var num03: Symbol { append("03") }
  public var num05: Symbol { append("05") }
  public var num04: Symbol { append("04") }
  public var num15: Symbol { append("15") }
  public var num3x2: Symbol { append("3x2") }
  public var num48: Symbol { append("48") }
  public var num75: Symbol { append("75") }
  public var num43: Symbol { append("43") }
  public var num3x3: Symbol { append("3x3") }
  public var num14: Symbol { append("14") }
  public var num25: Symbol { append("25") }
  public var num49: Symbol { append("49") }
  public var num2x2: Symbol { append("2x2") }
  public var num4a: Symbol { append("4a") }
  public var num30: Symbol { append("30") }
  public var num33: Symbol { append("33") }
  public var num4: Symbol { append("4") }
  public var num6: Symbol { append("6") }
  public var num20: Symbol { append("20") }
  public var num09: Symbol { append("09") }
  public var num60: Symbol { append("60") }
  public var num32: Symbol { append("32") }
  public var num50percent: Symbol { append("50percent") }
  public var num19: Symbol { append("19") }
  public var num25percent: Symbol { append("25percent") }
  public var num22: Symbol { append("22") }
  public var num12: Symbol { append("12") }
  public var num45: Symbol { append("45") }
  public var num123: Symbol { append("123") }
  public var num100: Symbol { append("100") }
  public var num41: Symbol { append("41") }
  public var num31: Symbol { append("31") }
  public var num16: Symbol { append("16") }
  public var num50: Symbol { append("50") }
  public var num3d: Symbol { append("3d") }
  public var num11: Symbol { append("11") }
  public var num44: Symbol { append("44") }
  public var num7: Symbol { append("7") }
  public var num40: Symbol { append("40") }
  public var num10: Symbol { append("10") }
  public var num90: Symbol { append("90") }
  public var num2h: Symbol { append("2h") }
  public var num35: Symbol { append("35") }
  public var num47: Symbol { append("47") }
  public var num4l: Symbol { append("4l") }
  public var num08: Symbol { append("08") }
  public var num06: Symbol { append("06") }
  public var `sidebar`: Symbol { append("sidebar") }
  public var `contact`: Symbol { append("contact") }
  public var `popcorn`: Symbol { append("popcorn") }
  public var `checkmark`: Symbol { append("checkmark") }
  public var `speedometer`: Symbol { append("speedometer") }
  public var `open`: Symbol { append("open") }
  public var `fuelpump`: Symbol { append("fuelpump") }
  public var `pickleball`: Symbol { append("pickleball") }
  public var `skis`: Symbol { append("skis") }
  public var `africa`: Symbol { append("africa") }
  public var `alarm`: Symbol { append("alarm") }
  public var `suit`: Symbol { append("suit") }
  public var `connector`: Symbol { append("connector") }
  public var `highlighter`: Symbol { append("highlighter") }
  public var `gift`: Symbol { append("gift") }
  public var `rtl`: Symbol { append("rtl") }
  public var `pull`: Symbol { append("pull") }
  public var `curved`: Symbol { append("curved") }
  public var `lane`: Symbol { append("lane") }
  public var `squareshape`: Symbol { append("squareshape") }
  public var `peacesign`: Symbol { append("peacesign") }
  public var `expand`: Symbol { append("expand") }
  public var `barcode`: Symbol { append("barcode") }
  public var `widget`: Symbol { append("widget") }
  public var `enter`: Symbol { append("enter") }
  public var `stick`: Symbol { append("stick") }
  public var `gu`: Symbol { append("gu") }
  public var `medium`: Symbol { append("medium") }
  public var `golf`: Symbol { append("golf") }
  public var `trash`: Symbol { append("trash") }
  public var `s`: Symbol { append("s") }
  public var `mustache`: Symbol { append("mustache") }
  public var `play`: Symbol { append("play") }
  public var `dpad`: Symbol { append("dpad") }
  public var `poweron`: Symbol { append("poweron") }
  public var `tag`: Symbol { append("tag") }
  public var `squash`: Symbol { append("squash") }
  public var `filled`: Symbol { append("filled") }
  public var `football`: Symbol { append("football") }
  public var `microwave`: Symbol { append("microwave") }
  public var `wiper`: Symbol { append("wiper") }
  public var `rugbyball`: Symbol { append("rugbyball") }
  public var `gyroscope`: Symbol { append("gyroscope") }
  public var `pin`: Symbol { append("pin") }
  public var `ladybug`: Symbol { append("ladybug") }
  public var `trianglepath`: Symbol { append("trianglepath") }
  public var `thumbsup`: Symbol { append("thumbsup") }
  public var `entry`: Symbol { append("entry") }
  public var `toilet`: Symbol { append("toilet") }
  public var `paperplane`: Symbol { append("paperplane") }
  public var `taillight`: Symbol { append("taillight") }
  public var `seats`: Symbol { append("seats") }
  public var `vision`: Symbol { append("vision") }
  public var `latch`: Symbol { append("latch") }
  public var `rolling`: Symbol { append("rolling") }
  public var `ellipse`: Symbol { append("ellipse") }
  public var `teddybear`: Symbol { append("teddybear") }
  public var `rain`: Symbol { append("rain") }
  public var `zh`: Symbol { append("zh") }
  public var `seated`: Symbol { append("seated") }
  public var `notequal`: Symbol { append("notequal") }
  public var `document`: Symbol { append("document") }
  public var `bank`: Symbol { append("bank") }
  public var `pencil`: Symbol { append("pencil") }
  public var `bubble`: Symbol { append("bubble") }
  public var `scooter`: Symbol { append("scooter") }
  public var `connection`: Symbol { append("connection") }
  public var `righttriangle`: Symbol { append("righttriangle") }
  public var `arrival`: Symbol { append("arrival") }
  public var `octagon`: Symbol { append("octagon") }
  public var `lsb`: Symbol { append("lsb") }
  public var `ipod`: Symbol { append("ipod") }
  public var `mediastick`: Symbol { append("mediastick") }
  public var `appwindow`: Symbol { append("appwindow") }
  public var `path`: Symbol { append("path") }
  public var `pinch`: Symbol { append("pinch") }
  public var `keypad`: Symbol { append("keypad") }
  public var `cursorarrow`: Symbol { append("cursorarrow") }
  public var `playpause`: Symbol { append("playpause") }
  public var `lt`: Symbol { append("lt") }
  public var `gymnastics`: Symbol { append("gymnastics") }
  public var `bin`: Symbol { append("bin") }
  public var `australian`: Symbol { append("australian") }
  public var `kashida`: Symbol { append("kashida") }
  public var `resize`: Symbol { append("resize") }
  public var `shadow`: Symbol { append("shadow") }
  public var `rainbow`: Symbol { append("rainbow") }
  public var `topleading`: Symbol { append("topleading") }
  public var `rays`: Symbol { append("rays") }
  public var `candybarphone`: Symbol { append("candybarphone") }
  public var `pills`: Symbol { append("pills") }
  public var `p2`: Symbol { append("p2") }
  public var `topmiddle`: Symbol { append("topmiddle") }
  public var `scanner`: Symbol { append("scanner") }
  public var `roll`: Symbol { append("roll") }
  public var `topthird`: Symbol { append("topthird") }
  public var `house`: Symbol { append("house") }
  public var `memorychip`: Symbol { append("memorychip") }
  public var `crescent`: Symbol { append("crescent") }
  public var `wand`: Symbol { append("wand") }
  public var `radio`: Symbol { append("radio") }
  public var `nairasign`: Symbol { append("nairasign") }
  public var `dc`: Symbol { append("dc") }
  public var `ipodshuffle`: Symbol { append("ipodshuffle") }
  public var `stars`: Symbol { append("stars") }
  public var `roundedbottom`: Symbol { append("roundedbottom") }
  public var `dot`: Symbol { append("dot") }
  public var `fishing`: Symbol { append("fishing") }
  public var `wrestling`: Symbol { append("wrestling") }
  public var `sailing`: Symbol { append("sailing") }
  public var `bonjour`: Symbol { append("bonjour") }
  public var `headlight`: Symbol { append("headlight") }
  public var `handbag`: Symbol { append("handbag") }
  public var `oilcan`: Symbol { append("oilcan") }
  public var `driveshaft`: Symbol { append("driveshaft") }
  public var `dock`: Symbol { append("dock") }
  public var `ultrawide`: Symbol { append("ultrawide") }
  public var `r4`: Symbol { append("r4") }
  public var `stroller`: Symbol { append("stroller") }
  public var `abs`: Symbol { append("abs") }
  public var `snowboarding`: Symbol { append("snowboarding") }
  public var `circle`: Symbol { append("circle") }
  public var `l2`: Symbol { append("l2") }
  public var `adjustable`: Symbol { append("adjustable") }
  public var `north`: Symbol { append("north") }
  public var `tip`: Symbol { append("tip") }
  public var `gobackward`: Symbol { append("gobackward") }
  public var `diagonalline`: Symbol { append("diagonalline") }
  public var `beam`: Symbol { append("beam") }
  public var `graduationcap`: Symbol { append("graduationcap") }
  public var `append`: Symbol { append("append") }
  public var `field`: Symbol { append("field") }
  public var `dongsign`: Symbol { append("dongsign") }
  public var `topright`: Symbol { append("topright") }
  public var `sports`: Symbol { append("sports") }
  public var `router`: Symbol { append("router") }
  public var `rb`: Symbol { append("rb") }
  public var `frontleft`: Symbol { append("frontleft") }
  public var `shoe`: Symbol { append("shoe") }
  public var `return`: Symbol { append("return") }
  public var `airpodpro`: Symbol { append("airpodpro") }
  public var `stop`: Symbol { append("stop") }
  public var `lb`: Symbol { append("lb") }
  public var `arrowshape`: Symbol { append("arrowshape") }
  public var `tsa`: Symbol { append("tsa") }
  public var `suspension`: Symbol { append("suspension") }
  public var `chineseyuanrenminbisign`: Symbol { append("chineseyuanrenminbisign") }
  public var `ccs2`: Symbol { append("ccs2") }
  public var `scalemass`: Symbol { append("scalemass") }
  public var `you`: Symbol { append("you") }
  public var `ellipsis`: Symbol { append("ellipsis") }
  public var `doc`: Symbol { append("doc") }
  public var `percent`: Symbol { append("percent") }
  public var `dress`: Symbol { append("dress") }
  public var `eyes`: Symbol { append("eyes") }
  public var `clock`: Symbol { append("clock") }
  public var `image`: Symbol { append("image") }
  public var `magsafe`: Symbol { append("magsafe") }
  public var `raid`: Symbol { append("raid") }
  public var `clockwise`: Symbol { append("clockwise") }
  public var `scatter`: Symbol { append("scatter") }
  public var `sequence`: Symbol { append("sequence") }
  public var `flask`: Symbol { append("flask") }
  public var `kn`: Symbol { append("kn") }
  public var `dottedunderline`: Symbol { append("dottedunderline") }
  public var `adapter`: Symbol { append("adapter") }
  public var `aspectratio`: Symbol { append("aspectratio") }
  public var `w`: Symbol { append("w") }
  public var `calendar`: Symbol { append("calendar") }
  public var `r3`: Symbol { append("r3") }
  public var `intervaltraining`: Symbol { append("intervaltraining") }
  public var `europe`: Symbol { append("europe") }
  public var `backward`: Symbol { append("backward") }
  public var `burn`: Symbol { append("burn") }
  public var `uturn`: Symbol { append("uturn") }
  public var `glowplug`: Symbol { append("glowplug") }
  public var `cloud`: Symbol { append("cloud") }
  public var `si`: Symbol { append("si") }
  public var `cedisign`: Symbol { append("cedisign") }
  public var `lightbulb`: Symbol { append("lightbulb") }
  public var `australsign`: Symbol { append("australsign") }
  public var `thermometer`: Symbol { append("thermometer") }
  public var `deskview`: Symbol { append("deskview") }
  public var `cellularbars`: Symbol { append("cellularbars") }
  public var `with`: Symbol { append("with") }
  public var `celsius`: Symbol { append("celsius") }
  public var `headphones`: Symbol { append("headphones") }
  public var `ascending`: Symbol { append("ascending") }
  public var `degreesign`: Symbol { append("degreesign") }
  public var `wrongwaysign`: Symbol { append("wrongwaysign") }
  public var `joystick`: Symbol { append("joystick") }
  public var `waveform`: Symbol { append("waveform") }
  public var `trianglehead`: Symbol { append("trianglehead") }
  public var `chair`: Symbol { append("chair") }
  public var `step`: Symbol { append("step") }
  public var `scissors`: Symbol { append("scissors") }
  public var `angledtop`: Symbol { append("angledtop") }
  public var `and`: Symbol { append("and") }
  public var `flipphone`: Symbol { append("flipphone") }
  public var `playstation`: Symbol { append("playstation") }
  public var `downhill`: Symbol { append("downhill") }
  public var `carrot`: Symbol { append("carrot") }
  public var `medical`: Symbol { append("medical") }
  public var `inverse`: Symbol { append("inverse") }
  public var `alignleft`: Symbol { append("alignleft") }
  public var `purchased`: Symbol { append("purchased") }
  public var `videoprojector`: Symbol { append("videoprojector") }
  public var `n`: Symbol { append("n") }
  public var `bottomhalf`: Symbol { append("bottomhalf") }
  public var `mic`: Symbol { append("mic") }
  public var `redaction`: Symbol { append("redaction") }
  public var `plaintext`: Symbol { append("plaintext") }
  public var `coloncurrencysign`: Symbol { append("coloncurrencysign") }
  public var `greetingcard`: Symbol { append("greetingcard") }
  public var `surfing`: Symbol { append("surfing") }
  public var `braille`: Symbol { append("braille") }
  public var `l1`: Symbol { append("l1") }
  public var `shower`: Symbol { append("shower") }
  public var `sat`: Symbol { append("sat") }
  public var `transmission`: Symbol { append("transmission") }
  public var `australiandollarsign`: Symbol { append("australiandollarsign") }
  public var `airpodspro`: Symbol { append("airpodspro") }
  public var `square`: Symbol { append("square") }
  public var `size`: Symbol { append("size") }
  public var `counterclockwise`: Symbol { append("counterclockwise") }
  public var `hazardsign`: Symbol { append("hazardsign") }
  public var `sparkles`: Symbol { append("sparkles") }
  public var `c`: Symbol { append("c") }
  public var `metering`: Symbol { append("metering") }
  public var `left`: Symbol { append("left") }
  public var `quote`: Symbol { append("quote") }
  public var `sleep`: Symbol { append("sleep") }
  public var `capsule`: Symbol { append("capsule") }
  public var `macro`: Symbol { append("macro") }
  public var `tennisball`: Symbol { append("tennisball") }
  public var `axel`: Symbol { append("axel") }
  public var `dishwasher`: Symbol { append("dishwasher") }
  public var `safetycone`: Symbol { append("safetycone") }
  public var `alt`: Symbol { append("alt") }
  public var `distribution`: Symbol { append("distribution") }
  public var `iphone`: Symbol { append("iphone") }
  public var `ar`: Symbol { append("ar") }
  public var `badminton`: Symbol { append("badminton") }
  public var `ecg`: Symbol { append("ecg") }
  public var `cross`: Symbol { append("cross") }
  public var `fresh`: Symbol { append("fresh") }
  public var `shoeprints`: Symbol { append("shoeprints") }
  public var `awning`: Symbol { append("awning") }
  public var `mount`: Symbol { append("mount") }
  public var `my`: Symbol { append("my") }
  public var `xbox`: Symbol { append("xbox") }
  public var `captions`: Symbol { append("captions") }
  public var `ceiling`: Symbol { append("ceiling") }
  public var `shareplay`: Symbol { append("shareplay") }
  public var `crosscountry`: Symbol { append("crosscountry") }
  public var `intermittent`: Symbol { append("intermittent") }
  public var `movieclapper`: Symbol { append("movieclapper") }
  public var `watch`: Symbol { append("watch") }
  public var `wind`: Symbol { append("wind") }
  public var `holdinghands`: Symbol { append("holdinghands") }
  public var `formfitting`: Symbol { append("formfitting") }
  public var `powerbeats`: Symbol { append("powerbeats") }
  public var `laptopcomputer`: Symbol { append("laptopcomputer") }
  public var `downtrend`: Symbol { append("downtrend") }
  public var `split`: Symbol { append("split") }
  public var `dice`: Symbol { append("dice") }
  public var `fan`: Symbol { append("fan") }
  public var `j`: Symbol { append("j") }
  public var `restart`: Symbol { append("restart") }
  public var `d`: Symbol { append("d") }
  public var `furniture`: Symbol { append("furniture") }
  public var `multiply`: Symbol { append("multiply") }
  public var `landscape`: Symbol { append("landscape") }
  public var `paintpalette`: Symbol { append("paintpalette") }
  public var `merge`: Symbol { append("merge") }
  public var `high`: Symbol { append("high") }
  public var `hockey`: Symbol { append("hockey") }
  public var `powerbeatspro`: Symbol { append("powerbeatspro") }
  public var `fluid`: Symbol { append("fluid") }
  public var `zzz`: Symbol { append("zzz") }
  public var `clap`: Symbol { append("clap") }
  public var `aperture`: Symbol { append("aperture") }
  public var `microbe`: Symbol { append("microbe") }
  public var `mountain`: Symbol { append("mountain") }
  public var `disengaged`: Symbol { append("disengaged") }
  public var `mini`: Symbol { append("mini") }
  public var `macmini`: Symbol { append("macmini") }
  public var `bases`: Symbol { append("bases") }
  public var `globe`: Symbol { append("globe") }
  public var `magicmouse`: Symbol { append("magicmouse") }
  public var `min`: Symbol { append("min") }
  public var `paragraphsign`: Symbol { append("paragraphsign") }
  public var `switch`: Symbol { append("switch") }
  public var `tower`: Symbol { append("tower") }
  public var `malaysianringgitsign`: Symbol { append("malaysianringgitsign") }
  public var `truck`: Symbol { append("truck") }
  public var `playground`: Symbol { append("playground") }
  public var `allergens`: Symbol { append("allergens") }
  public var `gear`: Symbol { append("gear") }
  public var `indianrupeesign`: Symbol { append("indianrupeesign") }
  public var `screwdriver`: Symbol { append("screwdriver") }
  public var `bicycle`: Symbol { append("bicycle") }
  public var `shekelsign`: Symbol { append("shekelsign") }
  public var `wifi`: Symbol { append("wifi") }
  public var `fanblades`: Symbol { append("fanblades") }
  public var `drop`: Symbol { append("drop") }
  public var `remote`: Symbol { append("remote") }
  public var `macstudio`: Symbol { append("macstudio") }
  public var `heat`: Symbol { append("heat") }
  public var `cooldown`: Symbol { append("cooldown") }
  public var `collision`: Symbol { append("collision") }
  public var `inhaler`: Symbol { append("inhaler") }
  public var `kickboxing`: Symbol { append("kickboxing") }
  public var `soccer`: Symbol { append("soccer") }
  public var `header`: Symbol { append("header") }
  public var `powermeter`: Symbol { append("powermeter") }
  public var `storefront`: Symbol { append("storefront") }
  public var `sleet`: Symbol { append("sleet") }
  public var `sos`: Symbol { append("sos") }
  public var `tachometer`: Symbol { append("tachometer") }
  public var `bell`: Symbol { append("bell") }
  public var `waterbottle`: Symbol { append("waterbottle") }
  public var `h`: Symbol { append("h") }
  public var `curvedto`: Symbol { append("curvedto") }
  public var `larger`: Symbol { append("larger") }
  public var `vial`: Symbol { append("vial") }
  public var `exit`: Symbol { append("exit") }
  public var `fish`: Symbol { append("fish") }
  public var `dollarsign`: Symbol { append("dollarsign") }
  public var `burst`: Symbol { append("burst") }
  public var `forwardslash`: Symbol { append("forwardslash") }
  public var `he`: Symbol { append("he") }
  public var `mug`: Symbol { append("mug") }
  public var `base`: Symbol { append("base") }
  public var `fire`: Symbol { append("fire") }
  public var `eurozonesign`: Symbol { append("eurozonesign") }
  public var `stair`: Symbol { append("stair") }
  public var `group`: Symbol { append("group") }
  public var `staroflife`: Symbol { append("staroflife") }
  public var `bottomrighthalf`: Symbol { append("bottomrighthalf") }
  public var `archivebox`: Symbol { append("archivebox") }
  public var `humidity`: Symbol { append("humidity") }
  public var `haze`: Symbol { append("haze") }
  public var `australia`: Symbol { append("australia") }
  public var `trailingthird`: Symbol { append("trailingthird") }
  public var `homebutton`: Symbol { append("homebutton") }
  public var `signature`: Symbol { append("signature") }
  public var `warninglight`: Symbol { append("warninglight") }
  public var `skateboarding`: Symbol { append("skateboarding") }
  public var `sharedwithyou`: Symbol { append("sharedwithyou") }
  public var `side`: Symbol { append("side") }
  public var `rectangle`: Symbol { append("rectangle") }
  public var `turn`: Symbol { append("turn") }
  public var `slash`: Symbol { append("slash") }
  public var `folder`: Symbol { append("folder") }
  public var `hand`: Symbol { append("hand") }
  public var `visionpro`: Symbol { append("visionpro") }
  public var `licenseplate`: Symbol { append("licenseplate") }
  public var `diagonal`: Symbol { append("diagonal") }
  public var `desktopcomputer`: Symbol { append("desktopcomputer") }
  public var `lefthalf`: Symbol { append("lefthalf") }
  public var `p3`: Symbol { append("p3") }
  public var `dance`: Symbol { append("dance") }
  public var `bn`: Symbol { append("bn") }
  public var `flip`: Symbol { append("flip") }
  public var `club`: Symbol { append("club") }
  public var `beach`: Symbol { append("beach") }
  public var `forward`: Symbol { append("forward") }
  public var `sunset`: Symbol { append("sunset") }
  public var `trailinghalf`: Symbol { append("trailinghalf") }
  public var `indoor`: Symbol { append("indoor") }
  public var `mono`: Symbol { append("mono") }
  public var `airplane`: Symbol { append("airplane") }
  public var `retarder`: Symbol { append("retarder") }
  public var `powerbeats3`: Symbol { append("powerbeats3") }
  public var `message`: Symbol { append("message") }
  public var `crown`: Symbol { append("crown") }
  public var `r`: Symbol { append("r") }
  public var `roof`: Symbol { append("roof") }
  public var `meter`: Symbol { append("meter") }
  public var `signal`: Symbol { append("signal") }
  public var `xmark`: Symbol { append("xmark") }
  public var `bus`: Symbol { append("bus") }
  public var `right`: Symbol { append("right") }
  public var `trailing`: Symbol { append("trailing") }
  public var `cylinder`: Symbol { append("cylinder") }
  public var `flattrend`: Symbol { append("flattrend") }
  public var `space`: Symbol { append("space") }
  public var `turkishlirasign`: Symbol { append("turkishlirasign") }
  public var `outdoor`: Symbol { append("outdoor") }
  public var `sizes`: Symbol { append("sizes") }
  public var `first`: Symbol { append("first") }
  public var `faxmachine`: Symbol { append("faxmachine") }
  public var `convertible`: Symbol { append("convertible") }
  public var `spot`: Symbol { append("spot") }
  public var `sensor`: Symbol { append("sensor") }
  public var `shift`: Symbol { append("shift") }
  public var `softball`: Symbol { append("softball") }
  public var `hryvniasign`: Symbol { append("hryvniasign") }
  public var `upper`: Symbol { append("upper") }
  public var `gym`: Symbol { append("gym") }
  public var `sportscourt`: Symbol { append("sportscourt") }
  public var `macwindow`: Symbol { append("macwindow") }
  public var `l4`: Symbol { append("l4") }
  public var `basketball`: Symbol { append("basketball") }
  public var `command`: Symbol { append("command") }
  public var `circlepath`: Symbol { append("circlepath") }
  public var `topleft`: Symbol { append("topleft") }
  public var `front`: Symbol { append("front") }
  public var `curling`: Symbol { append("curling") }
  public var `end`: Symbol { append("end") }
  public var `beziercurve`: Symbol { append("beziercurve") }
  public var `polishzlotysign`: Symbol { append("polishzlotysign") }
  public var `stack`: Symbol { append("stack") }
  public var `apps`: Symbol { append("apps") }
  public var `loupe`: Symbol { append("loupe") }
  public var `wonsign`: Symbol { append("wonsign") }
  public var `hearingdevice`: Symbol { append("hearingdevice") }
  public var `book`: Symbol { append("book") }
  public var `snowflake`: Symbol { append("snowflake") }
  public var `checked`: Symbol { append("checked") }
  public var `track`: Symbol { append("track") }
  public var `antenna`: Symbol { append("antenna") }
  public var `lanyardcard`: Symbol { append("lanyardcard") }
  public var `shazam`: Symbol { append("shazam") }
  public var `headset`: Symbol { append("headset") }
  public var `card`: Symbol { append("card") }
  public var `lessthanorequalto`: Symbol { append("lessthanorequalto") }
  public var `traditional`: Symbol { append("traditional") }
  public var `pointed`: Symbol { append("pointed") }
  public var `studentdesk`: Symbol { append("studentdesk") }
  public var `appclip`: Symbol { append("appclip") }
  public var `skating`: Symbol { append("skating") }
  public var `level`: Symbol { append("level") }
  public var `suv`: Symbol { append("suv") }
  public var `ml`: Symbol { append("ml") }
  public var `syringe`: Symbol { append("syringe") }
  public var `p4`: Symbol { append("p4") }
  public var `striped`: Symbol { append("striped") }
  public var `answer`: Symbol { append("answer") }
  public var `moonphase`: Symbol { append("moonphase") }
  public var `engine`: Symbol { append("engine") }
  public var `or`: Symbol { append("or") }
  public var `squarepath`: Symbol { append("squarepath") }
  public var `programmable`: Symbol { append("programmable") }
  public var `archery`: Symbol { append("archery") }
  public var `arabic`: Symbol { append("arabic") }
  public var `numbers`: Symbol { append("numbers") }
  public var `distribute`: Symbol { append("distribute") }
  public var `directcurrent`: Symbol { append("directcurrent") }
  public var `dioxide`: Symbol { append("dioxide") }
  public var `conditioner`: Symbol { append("conditioner") }
  public var `drawing`: Symbol { append("drawing") }
  public var `chargingcase`: Symbol { append("chargingcase") }
  public var `brakesignal`: Symbol { append("brakesignal") }
  public var `hearingaid`: Symbol { append("hearingaid") }
  public var `applewatch`: Symbol { append("applewatch") }
  public var `z`: Symbol { append("z") }
  public var `arts`: Symbol { append("arts") }
  public var `zl`: Symbol { append("zl") }
  public var `gamecontroller`: Symbol { append("gamecontroller") }
  public var `highintensity`: Symbol { append("highintensity") }
  public var `motion`: Symbol { append("motion") }
  public var `gen3`: Symbol { append("gen3") }
  public var `cylindrical`: Symbol { append("cylindrical") }
  public var `shade`: Symbol { append("shade") }
  public var `meditate`: Symbol { append("meditate") }
  public var `insert`: Symbol { append("insert") }
  public var `smiling`: Symbol { append("smiling") }
  public var `tree`: Symbol { append("tree") }
  public var `face`: Symbol { append("face") }
  public var `theatermasks`: Symbol { append("theatermasks") }
  public var `ko`: Symbol { append("ko") }
  public var `head`: Symbol { append("head") }
  public var `apple`: Symbol { append("apple") }
  public var `fit`: Symbol { append("fit") }
  public var `exclamation`: Symbol { append("exclamation") }
  public var `eyeglasses`: Symbol { append("eyeglasses") }
  public var `network`: Symbol { append("network") }
  public var `moon`: Symbol { append("moon") }
  public var `magazine`: Symbol { append("magazine") }
  public var `shield`: Symbol { append("shield") }
  public var `selection`: Symbol { append("selection") }
  public var `smiley`: Symbol { append("smiley") }
  public var `unit`: Symbol { append("unit") }
  public var `layout`: Symbol { append("layout") }
  public var `curlybraces`: Symbol { append("curlybraces") }
  public var `touchid`: Symbol { append("touchid") }
  public var `ratio`: Symbol { append("ratio") }
  public var `day`: Symbol { append("day") }
  public var `music`: Symbol { append("music") }
  public var `leadinghalf`: Symbol { append("leadinghalf") }
  public var `hi`: Symbol { append("hi") }
  public var `appletv`: Symbol { append("appletv") }
  public var `frying`: Symbol { append("frying") }
  public var `fencing`: Symbol { append("fencing") }
  public var `lungs`: Symbol { append("lungs") }
  public var `stand`: Symbol { append("stand") }
  public var `nacs`: Symbol { append("nacs") }
  public var `functional`: Symbol { append("functional") }
  public var `accelerator`: Symbol { append("accelerator") }
  public var `straw`: Symbol { append("straw") }
  public var `theatermask`: Symbol { append("theatermask") }
  public var `click`: Symbol { append("click") }
  public var `jack`: Symbol { append("jack") }
  public var `sparkle`: Symbol { append("sparkle") }
  public var `logo`: Symbol { append("logo") }
  public var `binoculars`: Symbol { append("binoculars") }
  public var `tram`: Symbol { append("tram") }
  public var `middleleft`: Symbol { append("middleleft") }
  public var `bottom`: Symbol { append("bottom") }
  public var `trianglebadge`: Symbol { append("trianglebadge") }
  public var `run`: Symbol { append("run") }
  public var `purifier`: Symbol { append("purifier") }
  public var `memories`: Symbol { append("memories") }
  public var `quarter`: Symbol { append("quarter") }
  public var `questionmark`: Symbol { append("questionmark") }
  public var `bookmark`: Symbol { append("bookmark") }
  public var `exclamationmark`: Symbol { append("exclamationmark") }
  public var `pianokeys`: Symbol { append("pianokeys") }
  public var `jumprope`: Symbol { append("jumprope") }
  public var `hexagongrid`: Symbol { append("hexagongrid") }
  public var `pesetasign`: Symbol { append("pesetasign") }
  public var `lamp`: Symbol { append("lamp") }
  public var `lightrail`: Symbol { append("lightrail") }
  public var `fahrenheit`: Symbol { append("fahrenheit") }
  public var `bitcoinsign`: Symbol { append("bitcoinsign") }
  public var `progress`: Symbol { append("progress") }
  public var `bottomthird`: Symbol { append("bottomthird") }
  public var `sixspeed`: Symbol { append("sixspeed") }
  public var `scale`: Symbol { append("scale") }
  public var `record`: Symbol { append("record") }
  public var `rublesign`: Symbol { append("rublesign") }
  public var `cycling`: Symbol { append("cycling") }
  public var `pool`: Symbol { append("pool") }
  public var `p1`: Symbol { append("p1") }
  public var `snowboard`: Symbol { append("snowboard") }
  public var `underline`: Symbol { append("underline") }
  public var `compact`: Symbol { append("compact") }
  public var `swatchpalette`: Symbol { append("swatchpalette") }
  public var `professional`: Symbol { append("professional") }
  public var `hifispeaker`: Symbol { append("hifispeaker") }
  public var `dust`: Symbol { append("dust") }
  public var `fitpro`: Symbol { append("fitpro") }
  public var `on`: Symbol { append("on") }
  public var `halffull`: Symbol { append("halffull") }
  public var `rosette`: Symbol { append("rosette") }
  public var `rugby`: Symbol { append("rugby") }
  public var `cursive`: Symbol { append("cursive") }
  public var `rectanglepath`: Symbol { append("rectanglepath") }
  public var `swim`: Symbol { append("swim") }
  public var `ribbon`: Symbol { append("ribbon") }
  public var `wineglass`: Symbol { append("wineglass") }
  public var `platter`: Symbol { append("platter") }
  public var `pano`: Symbol { append("pano") }
  public var `y`: Symbol { append("y") }
  public var `basket`: Symbol { append("basket") }
  public var `lounge`: Symbol { append("lounge") }
  public var `engaged`: Symbol { append("engaged") }
  public var `tablecells`: Symbol { append("tablecells") }
  public var `dotted`: Symbol { append("dotted") }
  public var `placeholdertext`: Symbol { append("placeholdertext") }
  public var `mosaic`: Symbol { append("mosaic") }
  public var `mph`: Symbol { append("mph") }
  public var `repeat`: Symbol { append("repeat") }
  public var `danishkronesign`: Symbol { append("danishkronesign") }
  public var `yaxis`: Symbol { append("yaxis") }
  public var `party`: Symbol { append("party") }
  public var `jacket`: Symbol { append("jacket") }
  public var `pro`: Symbol { append("pro") }
  public var `list`: Symbol { append("list") }
  public var `bolt`: Symbol { append("bolt") }
  public var `branch`: Symbol { append("branch") }
  public var `fill`: Symbol { append("fill") }
  public var `poweroff`: Symbol { append("poweroff") }
  public var `sterlingsign`: Symbol { append("sterlingsign") }
  public var `aqi`: Symbol { append("aqi") }
  public var `dumbbell`: Symbol { append("dumbbell") }
  public var `cable`: Symbol { append("cable") }
  public var `pattern`: Symbol { append("pattern") }
  public var `baseball`: Symbol { append("baseball") }
  public var `analog`: Symbol { append("analog") }
  public var `drone`: Symbol { append("drone") }
  public var `ant`: Symbol { append("ant") }
  public var `l3`: Symbol { append("l3") }
  public var `cart`: Symbol { append("cart") }
  public var `studiobudsplus`: Symbol { append("studiobudsplus") }
  public var `skateboard`: Symbol { append("skateboard") }
  public var `eye`: Symbol { append("eye") }
  public var `smallcircle`: Symbol { append("smallcircle") }
  public var `slowmo`: Symbol { append("slowmo") }
  public var `camera`: Symbol { append("camera") }
  public var `roundedtop`: Symbol { append("roundedtop") }
  public var `barometer`: Symbol { append("barometer") }
  public var `americas`: Symbol { append("americas") }
  public var `swift`: Symbol { append("swift") }
  public var `tropicalstorm`: Symbol { append("tropicalstorm") }
  public var `view`: Symbol { append("view") }
  public var `server`: Symbol { append("server") }
  public var `chandelier`: Symbol { append("chandelier") }
  public var `cricket`: Symbol { append("cricket") }
  public var `strip`: Symbol { append("strip") }
  public var `fireworks`: Symbol { append("fireworks") }
  public var `draw`: Symbol { append("draw") }
  public var `checklist`: Symbol { append("checklist") }
  public var `plus`: Symbol { append("plus") }
  public var `cpu`: Symbol { append("cpu") }
  public var `icloud`: Symbol { append("icloud") }
  public var `info`: Symbol { append("info") }
  public var `die`: Symbol { append("die") }
  public var `seatbelt`: Symbol { append("seatbelt") }
  public var `sunrise`: Symbol { append("sunrise") }
  public var `cabinet`: Symbol { append("cabinet") }
  public var `lowercase`: Symbol { append("lowercase") }
  public var `large`: Symbol { append("large") }
  public var `floor`: Symbol { append("floor") }
  public var `bottomrightquarter`: Symbol { append("bottomrightquarter") }
  public var `robotic`: Symbol { append("robotic") }
  public var `to`: Symbol { append("to") }
  public var `flag`: Symbol { append("flag") }
  public var `grid`: Symbol { append("grid") }
  public var `guitars`: Symbol { append("guitars") }
  public var `leading`: Symbol { append("leading") }
  public var `bird`: Symbol { append("bird") }
  public var `carrier`: Symbol { append("carrier") }
  public var `appletvremote`: Symbol { append("appletvremote") }
  public var `atom`: Symbol { append("atom") }
  public var `bed`: Symbol { append("bed") }
  public var `pedal`: Symbol { append("pedal") }
  public var `lineweight`: Symbol { append("lineweight") }
  public var `last`: Symbol { append("last") }
  public var `scribble`: Symbol { append("scribble") }
  public var `rotation`: Symbol { append("rotation") }
  public var `fog`: Symbol { append("fog") }
  public var `fall`: Symbol { append("fall") }
  public var `pill`: Symbol { append("pill") }
  public var `star`: Symbol { append("star") }
  public var `waxing`: Symbol { append("waxing") }
  public var `cursor`: Symbol { append("cursor") }
  public var `steeringwheel`: Symbol { append("steeringwheel") }
  public var `manatsign`: Symbol { append("manatsign") }
  public var `characters`: Symbol { append("characters") }
  public var `helmet`: Symbol { append("helmet") }
  public var `max`: Symbol { append("max") }
  public var `divide`: Symbol { append("divide") }
  public var `closed`: Symbol { append("closed") }
  public var `chademo`: Symbol { append("chademo") }
  public var `drive`: Symbol { append("drive") }
  public var `combustion`: Symbol { append("combustion") }
  public var `tuningfork`: Symbol { append("tuningfork") }
  public var `map`: Symbol { append("map") }
  public var `airpods`: Symbol { append("airpods") }
  public var `chevron`: Symbol { append("chevron") }
  public var `alternatingcurrent`: Symbol { append("alternatingcurrent") }
  public var `handheld`: Symbol { append("handheld") }
  public var `airplayaudio`: Symbol { append("airplayaudio") }
  public var `arrow`: Symbol { append("arrow") }
  public var `newspaper`: Symbol { append("newspaper") }
  public var `shuffle`: Symbol { append("shuffle") }
  public var `lines`: Symbol { append("lines") }
  public var `app`: Symbol { append("app") }
  public var `exclam`: Symbol { append("exclam") }
  public var `layers`: Symbol { append("layers") }
  public var `triangle`: Symbol { append("triangle") }
  public var `tilt`: Symbol { append("tilt") }
  public var `giftcard`: Symbol { append("giftcard") }
  public var `livephoto`: Symbol { append("livephoto") }
  public var `shippingbox`: Symbol { append("shippingbox") }
  public var `tengesign`: Symbol { append("tengesign") }
  public var `beats`: Symbol { append("beats") }
  public var `equestrian`: Symbol { append("equestrian") }
  public var `treadmill`: Symbol { append("treadmill") }
  public var `shock`: Symbol { append("shock") }
  public var `saucer`: Symbol { append("saucer") }
  public var `pause`: Symbol { append("pause") }
  public var `equal`: Symbol { append("equal") }
  public var `soccerball`: Symbol { append("soccerball") }
  public var `massage`: Symbol { append("massage") }
  public var `arrowtriangle`: Symbol { append("arrowtriangle") }
  public var `menucard`: Symbol { append("menucard") }
  public var `studiobuds`: Symbol { append("studiobuds") }
  public var `deskclock`: Symbol { append("deskclock") }
  public var `ev`: Symbol { append("ev") }
  public var `airpod`: Symbol { append("airpod") }
  public var `doubletap`: Symbol { append("doubletap") }
  public var `disc`: Symbol { append("disc") }
  public var `testtube`: Symbol { append("testtube") }
  public var `airpodsmax`: Symbol { append("airpodsmax") }
  public var `haptics`: Symbol { append("haptics") }
  public var `eurosign`: Symbol { append("eurosign") }
  public var `lessthan`: Symbol { append("lessthan") }
  public var `chart`: Symbol { append("chart") }
  public var `singaporedollarsign`: Symbol { append("singaporedollarsign") }
  public var `applescript`: Symbol { append("applescript") }
  public var `k`: Symbol { append("k") }
  public var `ibeam`: Symbol { append("ibeam") }
  public var `hill`: Symbol { append("hill") }
  public var `hail`: Symbol { append("hail") }
  public var `sailboat`: Symbol { append("sailboat") }
  public var `pa`: Symbol { append("pa") }
  public var `curtains`: Symbol { append("curtains") }
  public var `subscript`: Symbol { append("subscript") }
  public var `gibbous`: Symbol { append("gibbous") }
  public var `facing`: Symbol { append("facing") }
  public var `perspective`: Symbol { append("perspective") }
  public var `batterypack`: Symbol { append("batterypack") }
  public var `control`: Symbol { append("control") }
  public var `strengthtraining`: Symbol { append("strengthtraining") }
  public var `facemask`: Symbol { append("facemask") }
  public var `battery`: Symbol { append("battery") }
  public var `runningpace`: Symbol { append("runningpace") }
  public var `zigzag`: Symbol { append("zigzag") }
  public var `puzzlepiece`: Symbol { append("puzzlepiece") }
  public var `daytime`: Symbol { append("daytime") }
  public var `lightspectrum`: Symbol { append("lightspectrum") }
  public var `pyramid`: Symbol { append("pyramid") }
  public var `number`: Symbol { append("number") }
  public var `sdcard`: Symbol { append("sdcard") }
  public var `poweroutlet`: Symbol { append("poweroutlet") }
  public var `hare`: Symbol { append("hare") }
  public var `bahtsign`: Symbol { append("bahtsign") }
  public var `amplifier`: Symbol { append("amplifier") }
  public var `from`: Symbol { append("from") }
  public var `widebrim`: Symbol { append("widebrim") }
  public var `sofa`: Symbol { append("sofa") }
  public var `checkered`: Symbol { append("checkered") }
  public var `half`: Symbol { append("half") }
  public var `artframe`: Symbol { append("artframe") }
  public var `leaf`: Symbol { append("leaf") }
  public var `creditcard`: Symbol { append("creditcard") }
  public var `off`: Symbol { append("off") }
  public var `togglepower`: Symbol { append("togglepower") }
  public var `projective`: Symbol { append("projective") }
  public var `heater`: Symbol { append("heater") }
  public var `ruler`: Symbol { append("ruler") }
  public var `coaxial`: Symbol { append("coaxial") }
  public var `garage`: Symbol { append("garage") }
  public var `boxing`: Symbol { append("boxing") }
  public var `cardio`: Symbol { append("cardio") }
  public var `waning`: Symbol { append("waning") }
  public var `cube`: Symbol { append("cube") }
  public var `internaldrive`: Symbol { append("internaldrive") }
  public var `arcade`: Symbol { append("arcade") }
  public var `tugriksign`: Symbol { append("tugriksign") }
  public var `fx`: Symbol { append("fx") }
  public var `person`: Symbol { append("person") }
  public var `ice`: Symbol { append("ice") }
  public var `recessed`: Symbol { append("recessed") }
  public var `b`: Symbol { append("b") }
  public var `brake`: Symbol { append("brake") }
  public var `swap`: Symbol { append("swap") }
  public var `rack`: Symbol { append("rack") }
  public var `compress`: Symbol { append("compress") }
  public var `hiking`: Symbol { append("hiking") }
  public var `bold`: Symbol { append("bold") }
  public var `radiowaves`: Symbol { append("radiowaves") }
  public var `volleyball`: Symbol { append("volleyball") }
  public var `timeline`: Symbol { append("timeline") }
  public var `oven`: Symbol { append("oven") }
  public var `charger`: Symbol { append("charger") }
  public var `axle`: Symbol { append("axle") }
  public var `button`: Symbol { append("button") }
  public var `swedishkronasign`: Symbol { append("swedishkronasign") }
  public var `horn`: Symbol { append("horn") }
  public var `cat`: Symbol { append("cat") }
  public var `plug`: Symbol { append("plug") }
  public var `matter`: Symbol { append("matter") }
  public var `character`: Symbol { append("character") }
  public var `magnifyingglass`: Symbol { append("magnifyingglass") }
  public var `marks`: Symbol { append("marks") }
  public var `timelapse`: Symbol { append("timelapse") }
  public var `paintbrush`: Symbol { append("paintbrush") }
  public var `outline`: Symbol { append("outline") }
  public var `box`: Symbol { append("box") }
  public var `swirl`: Symbol { append("swirl") }
  public var `pickup`: Symbol { append("pickup") }
  public var `v`: Symbol { append("v") }
  public var `swiftdata`: Symbol { append("swiftdata") }
  public var `handball`: Symbol { append("handball") }
  public var `xaxis`: Symbol { append("xaxis") }
  public var `hurricane`: Symbol { append("hurricane") }
  public var `teletype`: Symbol { append("teletype") }
  public var `ru`: Symbol { append("ru") }
  public var `airplayvideo`: Symbol { append("airplayvideo") }
  public var `kipsign`: Symbol { append("kipsign") }
  public var `climbing`: Symbol { append("climbing") }
  public var `contextualmenu`: Symbol { append("contextualmenu") }
  public var `slider`: Symbol { append("slider") }
  public var `crossed`: Symbol { append("crossed") }
  public var `extreme`: Symbol { append("extreme") }
  public var `pie`: Symbol { append("pie") }
  public var `tent`: Symbol { append("tent") }
  public var `ja`: Symbol { append("ja") }
  public var `pip`: Symbol { append("pip") }
  public var `extralarge`: Symbol { append("extralarge") }
  public var `scroll`: Symbol { append("scroll") }
  public var `bottomleading`: Symbol { append("bottomleading") }
  public var `ta`: Symbol { append("ta") }
  public var `auto`: Symbol { append("auto") }
  public var `minus`: Symbol { append("minus") }
  public var `fireplace`: Symbol { append("fireplace") }
  public var `hanger`: Symbol { append("hanger") }
  public var `hover`: Symbol { append("hover") }
  public var `i`: Symbol { append("i") }
  public var `line`: Symbol { append("line") }
  public var `lock`: Symbol { append("lock") }
  public var `bubbles`: Symbol { append("bubbles") }
  public var `earphones`: Symbol { append("earphones") }
  public var `target`: Symbol { append("target") }
  public var `console`: Symbol { append("console") }
  public var `new`: Symbol { append("new") }
  public var `small`: Symbol { append("small") }
  public var `lanes`: Symbol { append("lanes") }
  public var `earbuds`: Symbol { append("earbuds") }
  public var `moonset`: Symbol { append("moonset") }
  public var `transparent`: Symbol { append("transparent") }
  public var `paragraph`: Symbol { append("paragraph") }
  public var `pilates`: Symbol { append("pilates") }
  public var `martial`: Symbol { append("martial") }
  public var `airport`: Symbol { append("airport") }
  public var `bust`: Symbol { append("bust") }
  public var `arkit`: Symbol { append("arkit") }
  public var `low`: Symbol { append("low") }
  public var `moonrise`: Symbol { append("moonrise") }
  public var `backpack`: Symbol { append("backpack") }
  public var `torus`: Symbol { append("torus") }
  public var `opticaldisc`: Symbol { append("opticaldisc") }
  public var `option`: Symbol { append("option") }
  public var `smoke`: Symbol { append("smoke") }
  public var `justifyleft`: Symbol { append("justifyleft") }
  public var `ivfluid`: Symbol { append("ivfluid") }
  public var `multispot`: Symbol { append("multispot") }
  public var `none`: Symbol { append("none") }
  public var `oar`: Symbol { append("oar") }
  public var `type`: Symbol { append("type") }
  public var `uppercase`: Symbol { append("uppercase") }
  public var `diamond`: Symbol { append("diamond") }
  public var `full`: Symbol { append("full") }
  public var `circlebadge`: Symbol { append("circlebadge") }
  public var `weighted`: Symbol { append("weighted") }
  public var `guaranisign`: Symbol { append("guaranisign") }
  public var `dots`: Symbol { append("dots") }
  public var `numbersign`: Symbol { append("numbersign") }
  public var `hitch`: Symbol { append("hitch") }
  public var `emission`: Symbol { append("emission") }
  public var `palm`: Symbol { append("palm") }
  public var `ipodtouch`: Symbol { append("ipodtouch") }
  public var `inward`: Symbol { append("inward") }
  public var `earpods`: Symbol { append("earpods") }
  public var `el`: Symbol { append("el") }
  public var `mecca`: Symbol { append("mecca") }
  public var `smartbatterycase`: Symbol { append("smartbatterycase") }
  public var `tv`: Symbol { append("tv") }
  public var `lodge`: Symbol { append("lodge") }
  public var `ccs1`: Symbol { append("ccs1") }
  public var `hourglass`: Symbol { append("hourglass") }
  public var `takeoutbag`: Symbol { append("takeoutbag") }
  public var `leftthird`: Symbol { append("leftthird") }
  public var `viewfinder`: Symbol { append("viewfinder") }
  public var `sheqelsign`: Symbol { append("sheqelsign") }
  public var `scurvepath`: Symbol { append("scurvepath") }
  public var `cruzeirosign`: Symbol { append("cruzeirosign") }
  public var `righthalf`: Symbol { append("righthalf") }
  public var `trophy`: Symbol { append("trophy") }
  public var `word`: Symbol { append("word") }
  public var `badge`: Symbol { append("badge") }
  public var `justify`: Symbol { append("justify") }
  public var `web`: Symbol { append("web") }
  public var `trapezoid`: Symbol { append("trapezoid") }
  public var `rightthird`: Symbol { append("rightthird") }
  public var `car`: Symbol { append("car") }
  public var `studiobud`: Symbol { append("studiobud") }
  public var `controlhandles`: Symbol { append("controlhandles") }
  public var `opticaldiscdrive`: Symbol { append("opticaldiscdrive") }
  public var `cooktop`: Symbol { append("cooktop") }
  public var `arrowtriangles`: Symbol { append("arrowtriangles") }
  public var `fiberchannel`: Symbol { append("fiberchannel") }
  public var `x`: Symbol { append("x") }
  public var `filemenu`: Symbol { append("filemenu") }
  public var `applepencil`: Symbol { append("applepencil") }
  public var `uiwindow`: Symbol { append("uiwindow") }
  public var `train`: Symbol { append("train") }
  public var `gen2`: Symbol { append("gen2") }
  public var `printer`: Symbol { append("printer") }
  public var `airbag`: Symbol { append("airbag") }
  public var `popper`: Symbol { append("popper") }
  public var `light`: Symbol { append("light") }
  public var `triangleshape`: Symbol { append("triangleshape") }
  public var `powerplug`: Symbol { append("powerplug") }
  public var `seal`: Symbol { append("seal") }
  public var `watchface`: Symbol { append("watchface") }
  public var `digitalcrown`: Symbol { append("digitalcrown") }
  public var `fork`: Symbol { append("fork") }
  public var `bullet`: Symbol { append("bullet") }
  public var `coat`: Symbol { append("coat") }
  public var `road`: Symbol { append("road") }
  public var `tire`: Symbol { append("tire") }
  public var `indicator`: Symbol { append("indicator") }
  public var `gb`: Symbol { append("gb") }
  public var `terminal`: Symbol { append("terminal") }
  public var `pentagon`: Symbol { append("pentagon") }
  public var `l`: Symbol { append("l") }
  public var `m1`: Symbol { append("m1") }
  public var `clipboard`: Symbol { append("clipboard") }
  public var `goforward`: Symbol { append("goforward") }
  public var `blinds`: Symbol { append("blinds") }
  public var `escape`: Symbol { append("escape") }
  public var `greaterthanorequalto`: Symbol { append("greaterthanorequalto") }
  public var `vacuum`: Symbol { append("vacuum") }
  public var `balloon`: Symbol { append("balloon") }
  public var `km`: Symbol { append("km") }
  public var `cargo`: Symbol { append("cargo") }
  public var `simcard`: Symbol { append("simcard") }
  public var `dog`: Symbol { append("dog") }
  public var `table`: Symbol { append("table") }
  public var `ball`: Symbol { append("ball") }
  public var `closing`: Symbol { append("closing") }
  public var `sink`: Symbol { append("sink") }
  public var `largecircle`: Symbol { append("largecircle") }
  public var `fibrechannel`: Symbol { append("fibrechannel") }
  public var `hifireceiver`: Symbol { append("hifireceiver") }
  public var `taichi`: Symbol { append("taichi") }
  public var `u`: Symbol { append("u") }
  public var `capslock`: Symbol { append("capslock") }
  public var `background`: Symbol { append("background") }
  public var `laser`: Symbol { append("laser") }
  public var `stereo`: Symbol { append("stereo") }
  public var `brain`: Symbol { append("brain") }
  public var `brazilianrealsign`: Symbol { append("brazilianrealsign") }
  public var `elliptical`: Symbol { append("elliptical") }
  public var `rsb`: Symbol { append("rsb") }
  public var `bifold`: Symbol { append("bifold") }
  public var `q`: Symbol { append("q") }
  public var `heart`: Symbol { append("heart") }
  public var `macbook`: Symbol { append("macbook") }
  public var `flashlight`: Symbol { append("flashlight") }
  public var `clear`: Symbol { append("clear") }
  public var `eyedropper`: Symbol { append("eyedropper") }
  public var `banknote`: Symbol { append("banknote") }
  public var `middleright`: Symbol { append("middleright") }
  public var `point`: Symbol { append("point") }
  public var `m4`: Symbol { append("m4") }
  public var `gen1`: Symbol { append("gen1") }
  public var `te`: Symbol { append("te") }
  public var `batteryblock`: Symbol { append("batteryblock") }
  public var `down`: Symbol { append("down") }
  public var `skiing`: Symbol { append("skiing") }
  public var `norwegiankronesign`: Symbol { append("norwegiankronesign") }
  public var `magnify`: Symbol { append("magnify") }
  public var `phone`: Symbol { append("phone") }
  public var `departure`: Symbol { append("departure") }
  public var `socialdance`: Symbol { append("socialdance") }
  public var `sunglasses`: Symbol { append("sunglasses") }
  public var `automatic`: Symbol { append("automatic") }
  public var `aligncenter`: Symbol { append("aligncenter") }
  public var `intersection`: Symbol { append("intersection") }
  public var `wheelchair`: Symbol { append("wheelchair") }
  public var `comb`: Symbol { append("comb") }
  public var `tophalf`: Symbol { append("tophalf") }
  public var `asia`: Symbol { append("asia") }
  public var `squareroot`: Symbol { append("squareroot") }
  public var `horizon`: Symbol { append("horizon") }
  public var `macpro`: Symbol { append("macpro") }
  public var `desk`: Symbol { append("desk") }
  public var `abc`: Symbol { append("abc") }
  public var `lower`: Symbol { append("lower") }
  public var `top`: Symbol { append("top") }
  public var `south`: Symbol { append("south") }
  public var `airplay`: Symbol { append("airplay") }
  public var `intelligence`: Symbol { append("intelligence") }
  public var `m`: Symbol { append("m") }
  public var `gearshift`: Symbol { append("gearshift") }
  public var `center`: Symbol { append("center") }
  public var `squares`: Symbol { append("squares") }
  public var `skew`: Symbol { append("skew") }
  public var `gate`: Symbol { append("gate") }
  public var `motorized`: Symbol { append("motorized") }
  public var `pc`: Symbol { append("pc") }
  public var `kph`: Symbol { append("kph") }
  public var `larisign`: Symbol { append("larisign") }
  public var `hands`: Symbol { append("hands") }
  public var `angle`: Symbol { append("angle") }
  public var `stove`: Symbol { append("stove") }
  public var `casement`: Symbol { append("casement") }
  public var `shell`: Symbol { append("shell") }
  public var `scope`: Symbol { append("scope") }
  public var `filters`: Symbol { append("filters") }
  public var `portrait`: Symbol { append("portrait") }
  public var `cap`: Symbol { append("cap") }
  public var `checkerboard`: Symbol { append("checkerboard") }
  public var `ipad`: Symbol { append("ipad") }
  public var `recordingtape`: Symbol { append("recordingtape") }
  public var `duployan`: Symbol { append("duployan") }
  public var `flexibility`: Symbol { append("flexibility") }
  public var `unchecked`: Symbol { append("unchecked") }
  public var `flame`: Symbol { append("flame") }
  public var `coolant`: Symbol { append("coolant") }
  public var `figure`: Symbol { append("figure") }
  public var `cycle`: Symbol { append("cycle") }
  public var `unknown`: Symbol { append("unknown") }
  public var `computermouse`: Symbol { append("computermouse") }
  public var `video`: Symbol { append("video") }
  public var `clutch`: Symbol { append("clutch") }
  public var `up`: Symbol { append("up") }
  public var `translate`: Symbol { append("translate") }
  public var `eject`: Symbol { append("eject") }
  public var `timer`: Symbol { append("timer") }
  public var `oval`: Symbol { append("oval") }
  public var `zipper`: Symbol { append("zipper") }
  public var `asterisk`: Symbol { append("asterisk") }
  public var `personalhotspot`: Symbol { append("personalhotspot") }
  public var `location`: Symbol { append("location") }
  public var `rotate`: Symbol { append("rotate") }
  public var `shared`: Symbol { append("shared") }
  public var `windshield`: Symbol { append("windshield") }
  public var `indent`: Symbol { append("indent") }
  public var `note`: Symbol { append("note") }
  public var `mr`: Symbol { append("mr") }
  public var `sum`: Symbol { append("sum") }
  public var `delete`: Symbol { append("delete") }
  public var `toptrailing`: Symbol { append("toptrailing") }
  public var `refrigerator`: Symbol { append("refrigerator") }
  public var `tornado`: Symbol { append("tornado") }
  public var `cake`: Symbol { append("cake") }
  public var `traction`: Symbol { append("traction") }
  public var `surfboard`: Symbol { append("surfboard") }
  public var `wake`: Symbol { append("wake") }
  public var `display`: Symbol { append("display") }
  public var `dotmatrix`: Symbol { append("dotmatrix") }
  public var `solobuds`: Symbol { append("solobuds") }
  public var `nose`: Symbol { append("nose") }
  public var `profile`: Symbol { append("profile") }
  public var `variable`: Symbol { append("variable") }
  public var `at`: Symbol { append("at") }
  public var `mouth`: Symbol { append("mouth") }
  public var `stairs`: Symbol { append("stairs") }
  public var `briefcase`: Symbol { append("briefcase") }
  public var `tunnel`: Symbol { append("tunnel") }
  public var `walk`: Symbol { append("walk") }
  public var `infinity`: Symbol { append("infinity") }
  public var `paper`: Symbol { append("paper") }
  public var `spade`: Symbol { append("spade") }
  public var `express`: Symbol { append("express") }
  public var `double`: Symbol { append("double") }
  public var `out`: Symbol { append("out") }
  public var `fn`: Symbol { append("fn") }
  public var `backrest`: Symbol { append("backrest") }
  public var `rowing`: Symbol { append("rowing") }
  public var `shutter`: Symbol { append("shutter") }
  public var `wave`: Symbol { append("wave") }
  public var `switcher`: Symbol { append("switcher") }
  public var `microphone`: Symbol { append("microphone") }
  public var `flowchart`: Symbol { append("flowchart") }
  public var `stopwatch`: Symbol { append("stopwatch") }
  public var `key`: Symbol { append("key") }
  public var `power`: Symbol { append("power") }
  public var `smartphone`: Symbol { append("smartphone") }
  public var `books`: Symbol { append("books") }
  public var `speaker`: Symbol { append("speaker") }
  public var `centsign`: Symbol { append("centsign") }
  public var `door`: Symbol { append("door") }
  public var `partition`: Symbol { append("partition") }
  public var `externaldrive`: Symbol { append("externaldrive") }
  public var `bottommiddle`: Symbol { append("bottommiddle") }
  public var `eraser`: Symbol { append("eraser") }
  public var `ring`: Symbol { append("ring") }
  public var `dashed`: Symbol { append("dashed") }
  public var `autostartstop`: Symbol { append("autostartstop") }
  public var `monoxide`: Symbol { append("monoxide") }
  public var `bowling`: Symbol { append("bowling") }
  public var `humidifier`: Symbol { append("humidifier") }
  public var `mediabox`: Symbol { append("mediabox") }
  public var `blast`: Symbol { append("blast") }
  public var `tirepressure`: Symbol { append("tirepressure") }
  public var `more`: Symbol { append("more") }
  public var `lirasign`: Symbol { append("lirasign") }
  public var `pass`: Symbol { append("pass") }
  public var `dial`: Symbol { append("dial") }
  public var `panel`: Symbol { append("panel") }
  public var `peruviansolessign`: Symbol { append("peruviansolessign") }
  public var `f`: Symbol { append("f") }
  public var `superscript`: Symbol { append("superscript") }
  public var `safari`: Symbol { append("safari") }
  public var `fitness`: Symbol { append("fitness") }
  public var `barre`: Symbol { append("barre") }
  public var `gauge`: Symbol { append("gauge") }
  public var `keyboard`: Symbol { append("keyboard") }
  public var `bottomright`: Symbol { append("bottomright") }
  public var `opticid`: Symbol { append("opticid") }
  public var `mni`: Symbol { append("mni") }
  public var `core`: Symbol { append("core") }
  public var `rhombus`: Symbol { append("rhombus") }
  public var `window`: Symbol { append("window") }
  public var `powercord`: Symbol { append("powercord") }
  public var `inset`: Symbol { append("inset") }
  public var `yoga`: Symbol { append("yoga") }
  public var `voiceover`: Symbol { append("voiceover") }
  public var `a`: Symbol { append("a") }
  public var `quarternote`: Symbol { append("quarternote") }
  public var `parentheses`: Symbol { append("parentheses") }
  public var `rupeesign`: Symbol { append("rupeesign") }
  public var `fingers`: Symbol { append("fingers") }
  public var `menubar`: Symbol { append("menubar") }
  public var `move`: Symbol { append("move") }
  public var `building`: Symbol { append("building") }
  public var `child`: Symbol { append("child") }
  public var `gen4`: Symbol { append("gen4") }
  public var `megaphone`: Symbol { append("megaphone") }
  public var `arms`: Symbol { append("arms") }
  public var `powersleep`: Symbol { append("powersleep") }
  public var `racket`: Symbol { append("racket") }
  public var `press`: Symbol { append("press") }
  public var `fossil`: Symbol { append("fossil") }
  public var `timemachine`: Symbol { append("timemachine") }
  public var `parkinglight`: Symbol { append("parkinglight") }
  public var `e`: Symbol { append("e") }
  public var `of`: Symbol { append("of") }
  public var `av`: Symbol { append("av") }
  public var `spread`: Symbol { append("spread") }
  public var `descent`: Symbol { append("descent") }
  public var `drizzle`: Symbol { append("drizzle") }
  public var `plusminus`: Symbol { append("plusminus") }
  public var `bar`: Symbol { append("bar") }
  public var `circulate`: Symbol { append("circulate") }
  public var `audio`: Symbol { append("audio") }
  public var `smaller`: Symbol { append("smaller") }
  public var `film`: Symbol { append("film") }
  public var `homekit`: Symbol { append("homekit") }
  public var `average`: Symbol { append("average") }
  public var `partial`: Symbol { append("partial") }
  public var `led`: Symbol { append("led") }
  public var `below`: Symbol { append("below") }
  public var `frame`: Symbol { append("frame") }
  public var `compass`: Symbol { append("compass") }
  public var `zr`: Symbol { append("zr") }
  public var `snow`: Symbol { append("snow") }
  public var `air`: Symbol { append("air") }
  public var `rt`: Symbol { append("rt") }
  public var `umbrella`: Symbol { append("umbrella") }
  public var `th`: Symbol { append("th") }
  public var `uptrend`: Symbol { append("uptrend") }
  public var `dehumidifier`: Symbol { append("dehumidifier") }
  public var `signpost`: Symbol { append("signpost") }
  public var `spray`: Symbol { append("spray") }
  public var `ac`: Symbol { append("ac") }
  public var `m3`: Symbol { append("m3") }
  public var `rm`: Symbol { append("rm") }
  public var `textbox`: Symbol { append("textbox") }
  public var `parkingsign`: Symbol { append("parkingsign") }
  public var `hat`: Symbol { append("hat") }
  public var `decrease`: Symbol { append("decrease") }
  public var `page`: Symbol { append("page") }
  public var `link`: Symbol { append("link") }
  public var `waterpolo`: Symbol { append("waterpolo") }
  public var `usb`: Symbol { append("usb") }
  public var `envelope`: Symbol { append("envelope") }
  public var `french`: Symbol { append("french") }
  public var `wrench`: Symbol { append("wrench") }
  public var `dottedline`: Symbol { append("dottedline") }
  public var `pesosign`: Symbol { append("pesosign") }
  public var `squeeze`: Symbol { append("squeeze") }
  public var `hammer`: Symbol { append("hammer") }
  public var `pipe`: Symbol { append("pipe") }
  public var `wireless`: Symbol { append("wireless") }
  public var `textformat`: Symbol { append("textformat") }
  public var `spacing`: Symbol { append("spacing") }
  public var `sliding`: Symbol { append("sliding") }
  public var `tap`: Symbol { append("tap") }
  public var `motionlines`: Symbol { append("motionlines") }
  public var `faceid`: Symbol { append("faceid") }
  public var `tray`: Symbol { append("tray") }
  public var `helm`: Symbol { append("helm") }
  public var `pages`: Symbol { append("pages") }
  public var `heavyrain`: Symbol { append("heavyrain") }
  public var `align`: Symbol { append("align") }
  public var `training`: Symbol { append("training") }
  public var `esim`: Symbol { append("esim") }
  public var `cup`: Symbol { append("cup") }
  public var `yensign`: Symbol { append("yensign") }
  public var `eyebrow`: Symbol { append("eyebrow") }
  public var `lightswitch`: Symbol { append("lightswitch") }
  public var `medal`: Symbol { append("medal") }
  public var `justifyright`: Symbol { append("justifyright") }
  public var `xyaxis`: Symbol { append("xyaxis") }
  public var `sun`: Symbol { append("sun") }
  public var `accessibility`: Symbol { append("accessibility") }
  public var `distance`: Symbol { append("distance") }
  public var `thumbsdown`: Symbol { append("thumbsdown") }
  public var `hex`: Symbol { append("hex") }
  public var `florinsign`: Symbol { append("florinsign") }
  public var `r1`: Symbol { append("r1") }
  public var `ferry`: Symbol { append("ferry") }
  public var `racquetball`: Symbol { append("racquetball") }
  public var `liquid`: Symbol { append("liquid") }
  public var `rectangular`: Symbol { append("rectangular") }
  public var `outward`: Symbol { append("outward") }
  public var `hold`: Symbol { append("hold") }
  public var `pedestrian`: Symbol { append("pedestrian") }
  public var `increase`: Symbol { append("increase") }
  public var `rearleft`: Symbol { append("rearleft") }
  public var `doorbell`: Symbol { append("doorbell") }
  public var `pan`: Symbol { append("pan") }
  public var `mail`: Symbol { append("mail") }
  public var `opening`: Symbol { append("opening") }
  public var `doubledecker`: Symbol { append("doubledecker") }
  public var `trunk`: Symbol { append("trunk") }
  public var `m2`: Symbol { append("m2") }
  public var `photo`: Symbol { append("photo") }
  public var `leadingthird`: Symbol { append("leadingthird") }
  public var `xserve`: Symbol { append("xserve") }
  public var `fleuron`: Symbol { append("fleuron") }
  public var `dash`: Symbol { append("dash") }
  public var `francsign`: Symbol { append("francsign") }
  public var `rower`: Symbol { append("rower") }
  public var `paperclip`: Symbol { append("paperclip") }
  public var `ear`: Symbol { append("ear") }
  public var `hunting`: Symbol { append("hunting") }
  public var `lm`: Symbol { append("lm") }
  public var `sprinkler`: Symbol { append("sprinkler") }
  public var `frontright`: Symbol { append("frontright") }
  public var `tow`: Symbol { append("tow") }
  public var `american`: Symbol { append("american") }
  public var `ellipses`: Symbol { append("ellipses") }
  public var `oscillation`: Symbol { append("oscillation") }
  public var `qrcode`: Symbol { append("qrcode") }
  public var `lacrosse`: Symbol { append("lacrosse") }
  public var `roman`: Symbol { append("roman") }
  public var `rearright`: Symbol { append("rearright") }
  public var `puck`: Symbol { append("puck") }
  public var `yieldsign`: Symbol { append("yieldsign") }
  public var `circles`: Symbol { append("circles") }
  public var `moped`: Symbol { append("moped") }
  public var `remove`: Symbol { append("remove") }
  public var `lizard`: Symbol { append("lizard") }
  public var `paddleshifter`: Symbol { append("paddleshifter") }
  public var `carseat`: Symbol { append("carseat") }
  public var `horizontal`: Symbol { append("horizontal") }
  public var `arrowkeys`: Symbol { append("arrowkeys") }
  public var `hexagon`: Symbol { append("hexagon") }
  public var `alignright`: Symbol { append("alignright") }
  public var `lasso`: Symbol { append("lasso") }
  public var `angled`: Symbol { append("angled") }
  public var `washer`: Symbol { append("washer") }
  public var `connected`: Symbol { append("connected") }
  public var `stethoscope`: Symbol { append("stethoscope") }
  public var `measurement`: Symbol { append("measurement") }
  public var `greaterthan`: Symbol { append("greaterthan") }
  public var `touch`: Symbol { append("touch") }
  public var `overhead`: Symbol { append("overhead") }
  public var `needle`: Symbol { append("needle") }
  public var `o`: Symbol { append("o") }
  public var `onehanded`: Symbol { append("onehanded") }
  public var `applelogo`: Symbol { append("applelogo") }
  public var `case`: Symbol { append("case") }
  public var `homepodmini`: Symbol { append("homepodmini") }
  public var `suitcase`: Symbol { append("suitcase") }
  public var `richtext`: Symbol { append("richtext") }
  public var `mind`: Symbol { append("mind") }
  public var `tennis`: Symbol { append("tennis") }
  public var `tortoise`: Symbol { append("tortoise") }
  public var `outs`: Symbol { append("outs") }
  public var `quotelevel`: Symbol { append("quotelevel") }
  public var `function`: Symbol { append("function") }
  public var `angledbottom`: Symbol { append("angledbottom") }
  public var `capsulepath`: Symbol { append("capsulepath") }
  public var `motorcycle`: Symbol { append("motorcycle") }
  public var `hexagonpath`: Symbol { append("hexagonpath") }
  public var `millsign`: Symbol { append("millsign") }
  public var `rear`: Symbol { append("rear") }
  public var `pawprint`: Symbol { append("pawprint") }
  public var `r2`: Symbol { append("r2") }
  public var `phonetic`: Symbol { append("phonetic") }
  public var `t`: Symbol { append("t") }
  public var `water`: Symbol { append("water") }
  public var `element`: Symbol { append("element") }
  public var `tshirt`: Symbol { append("tshirt") }
  public var `bottomleft`: Symbol { append("bottomleft") }
  public var `metronome`: Symbol { append("metronome") }
  public var `in`: Symbol { append("in") }
  public var `central`: Symbol { append("central") }
  public var `matrix`: Symbol { append("matrix") }
  public var `roller`: Symbol { append("roller") }
  public var `swipe`: Symbol { append("swipe") }
  public var `lever`: Symbol { append("lever") }
  public var `crop`: Symbol { append("crop") }
  public var `mixed`: Symbol { append("mixed") }
  public var `raised`: Symbol { append("raised") }
  public var `wide`: Symbol { append("wide") }
  public var `offgrid`: Symbol { append("offgrid") }
  public var `curvepath`: Symbol { append("curvepath") }
  public var `body`: Symbol { append("body") }
  public var `bandage`: Symbol { append("bandage") }
  public var `homepod`: Symbol { append("homepod") }
  public var `p`: Symbol { append("p") }
  public var `laurel`: Symbol { append("laurel") }
  public var `cablecar`: Symbol { append("cablecar") }
  public var `nosign`: Symbol { append("nosign") }
  public var `bag`: Symbol { append("bag") }
  public var `sidejet`: Symbol { append("sidejet") }
  public var `firewall`: Symbol { append("firewall") }
  public var `beacon`: Symbol { append("beacon") }
  public var `text`: Symbol { append("text") }
  public var `bounce`: Symbol { append("bounce") }
  public var `bay`: Symbol { append("bay") }
  public var `bottomtrailing`: Symbol { append("bottomtrailing") }
  public var `sutton`: Symbol { append("sutton") }
  public var `mappin`: Symbol { append("mappin") }
  public var `extinguisher`: Symbol { append("extinguisher") }
  public var `waves`: Symbol { append("waves") }
  public var `droplets`: Symbol { append("droplets") }
  public var `carbon`: Symbol { append("carbon") }
  public var `mirror`: Symbol { append("mirror") }
  public var `spigot`: Symbol { append("spigot") }
  public var `middle`: Symbol { append("middle") }
  public var `italic`: Symbol { append("italic") }
  public var `extension`: Symbol { append("extension") }
  public var `ticket`: Symbol { append("ticket") }
  public var `filter`: Symbol { append("filter") }
  public var `knife`: Symbol { append("knife") }
  public var `lifepreserver`: Symbol { append("lifepreserver") }
  public var `stepper`: Symbol { append("stepper") }
  public var `duffle`: Symbol { append("duffle") }
  public var `strikethrough`: Symbol { append("strikethrough") }
  public var `bathtub`: Symbol { append("bathtub") }
  public var `birthday`: Symbol { append("birthday") }
  public var `gearshape`: Symbol { append("gearshape") }
  public var `wallet`: Symbol { append("wallet") }
  public var `columns`: Symbol { append("columns") }
  public var `dryer`: Symbol { append("dryer") }
  public var `g`: Symbol { append("g") }
  public var `airtag`: Symbol { append("airtag") }
  public var `cone`: Symbol { append("cone") }
  public var `vertical`: Symbol { append("vertical") }
}